version: "3"

services:

  node:
    build: .
    command: ['npm', 'run', 'start']
    volumes:
      - ./docs/css:/usr/src/app/css:cached
      - ./docs/js:/usr/src/app/js:cached
      - ./docs/scss:/usr/src/app/scss:cached
